[terminal]
# Login is required for fish to load up correctly
shell = { program = "/opt/homebrew/bin/fish", args = ["--login"] }

# [font]
# size = 14

[keyboard]
# bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[window]
option_as_alt = "Both"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"
